basic.showIcon(IconNames.Heart)
Tinybit.RGB_Car_Big(Tinybit.enColor.OFF)
basic.forever(function () {
    Tinybit.RGB_Car_Big(Tinybit.enColor.Green)
    basic.pause(1000)
    Tinybit.RGB_Car_Big(Tinybit.enColor.Green)
    basic.pause(1000)
    Tinybit.RGB_Car_Big(Tinybit.enColor.Cyan)
    basic.pause(1000)
    Tinybit.RGB_Car_Big(Tinybit.enColor.Pinkish)
    basic.pause(1000)
    Tinybit.RGB_Car_Big(Tinybit.enColor.Yellow)
    basic.pause(1000)
})
